### Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  include:
    - if: branch = master OR tag IS present
      stage: "Documentation"
      julia: 1.2
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - |
          julia --color=yes --project=docs/ -e'
            using Pkg
            Pkg.add(PackageSpec(name="MLJBase", rev="master"));Pkg.add(PackageSpec(name="MLJTuning", rev="master"));Pkg.add(PackageSpec(name="MLJModels", rev="master"));Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
          '  

after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
