
[MultivariateStats.RidgeRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":load_path" = "MLJModels.MultivariateStats_.RidgeRegressor"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_name" = "MultivariateStats"
":name" = "RidgeRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[MultivariateStats.PCA]
":input_is_multivariate" = "`true`"
":package_uuid" = "6f286f6a-111f-5878-ab1e-185364afe411"
":output_scitype_union" = "`MLJBase.Continuous`"
":load_path" = "MLJModels.MultivariateStats_.PCA"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/MultivariateStats.jl"
":package_name" = "MultivariateStats"
":name" = "PCA"
":output_is_multivariate" = "`true`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[DecisionTree.DecisionTreeRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeRegressor"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":name" = "DecisionTreeRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[DecisionTree.DecisionTreeClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
":load_path" = "MLJModels.DecisionTree_.DecisionTreeClassifier"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/bensadeghi/DecisionTree.jl"
":package_name" = "DecisionTree"
":name" = "DecisionTreeClassifier"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMLClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLClassifier"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLClassifier"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMNuClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuClassifier"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuClassifier"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.ElasticNet]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.ElasticNet"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "ElasticNet"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.ElasticNetCV]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.ElasticNetCV"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "ElasticNetCV"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMRegressor"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMClassifier"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMClassifier"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMLRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMLRegressor"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMLRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[ScikitLearn.SVMNuRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
":load_path" = "MLJModels.ScikitLearn_.SVMNuRegressor"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/cstjean/ScikitLearn.jl"
":package_name" = "ScikitLearn"
":name" = "SVMNuRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.EpsilonSVR]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.EpsilonSVR"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "EpsilonSVR"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.LinearSVC]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.LinearSVC"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "LinearSVC"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.NuSVR]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.NuSVR"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "NuSVR"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.NuSVC]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.NuSVC"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "NuSVC"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.SVC]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":load_path" = "MLJModels.LIBSVM_.SVC"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "SVC"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[LIBSVM.OneClassSVM]
":input_is_multivariate" = "`true`"
":package_uuid" = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
":output_scitype_union" = "`MLJBase.Finite{2}`"
":load_path" = "MLJModels.LIBSVM_.OneClassSVM"
":is_pure_julia" = "`false`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/mpastell/LIBSVM.jl"
":package_name" = "LIBSVM"
":name" = "OneClassSVM"
":output_is_multivariate" = "`true`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[Clustering.KMeans]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":output_scitype_union" = "`MLJBase.Continuous`"
":load_path" = "MLJModels.Clustering_.KMeans"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMeans"
":output_is_multivariate" = "`true`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[Clustering.KMedoids]
":input_is_multivariate" = "`true`"
":package_uuid" = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
":output_scitype_union" = "`MLJBase.Continuous`"
":load_path" = "MLJModels.Clustering_.KMedoids"
":is_pure_julia" = "`true`"
":is_supervised" = "`false`"
":package_url" = "https://github.com/JuliaStats/Clustering.jl"
":package_name" = "Clustering"
":name" = "KMedoids"
":output_is_multivariate" = "`true`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[GLM.OLSRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.OLSRegressor"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "OLSRegressor"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[GLM.GLMCountRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
":load_path" = "MLJModels.GLM_.GLMCountRegressor"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/JuliaStats/GLM.jl"
":package_name" = "GLM"
":name" = "GLMCountRegressor"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Count`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[NaiveBayes.GaussianNBClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":load_path" = "MLJModels.NaiveBayes_.GaussianNBClassifier"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_name" = "NaiveBayes"
":name" = "GaussianNBClassifier"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[NaiveBayes.MultinomialNBClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
":load_path" = "MLJModels.NaiveBayes_.MultinomialNBClassifier"
":is_pure_julia" = "`true`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dfdx/NaiveBayes.jl"
":package_name" = "NaiveBayes"
":name" = "MultinomialNBClassifier"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Count`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostCount]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostCount"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostCount"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Count`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostRegressor]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostRegressor"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostRegressor"
":is_probabilistic" = "`false`"
":target_scitype_union" = "`MLJBase.Continuous`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"

[XGBoost.XGBoostClassifier]
":input_is_multivariate" = "`true`"
":package_uuid" = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
":load_path" = "MLJModels.XGBoost_.XGBoostClassifier"
":is_pure_julia" = "`false`"
":is_supervised" = "`true`"
":package_url" = "https://github.com/dmlc/XGBoost.jl"
":package_name" = "XGBoost"
":name" = "XGBoostClassifier"
":is_probabilistic" = "`true`"
":target_scitype_union" = "`MLJBase.Finite`"
":input_scitype_union" = "`MLJBase.Continuous`"
":is_wrapper" = "`false`"
