MultivariateStats = ["ICA", "RidgeRegressor", "KernelPCA", "PCA"]
DecisionTree = ["DecisionTreeRegressor", "DecisionTreeClassifier"]
ScikitLearn = ["SVMRegressor", "SVMNuClassifier", "ElasticNet", "ElasticNetCV", "SVMClassifier", "SVMLRegressor", "SVMNuRegressor", "SVMLClassifier"]
LIBSVM = ["EpsilonSVR", "LinearSVC", "NuSVR", "NuSVC", "SVC", "OneClassSVM"]
Clustering = ["KMeans", "KMedoids"]
GLM = ["OLSRegressor", "GLMCountRegressor"]
NaiveBayes = ["GaussianNBClassifier", "MultinomialNBClassifier"]
XGBoost = ["XGBoostCount", "XGBoostRegressor", "XGBoostClassifier"]
