[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NaiveBayes = "9bbee03b-0db5-5f46-924f-b5c9c21b8c60"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
MLJBase = "0.2.0"
MLJModels = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
